### ISSUE TITLE
list of players online with their ip's

### ISSUE THREAD

**Issue by tflament** [alecgorge/jsonapi#372]
Hello, 

Is this possible with jsonapi return an array with the list of connected players and their ip's. 

I currently use the players.online method that allows me to have this information, but the informations returned by this function are heavy, hence my request to get only the list of players and their corresponding ip's 

Thank you in advance!

**Comment by Nydau** [comment]
Hello!
The change of nickname arriving very soon I will like to know if it is possible to have the same method with UUIDs (and without nickname).
Thank you in advance,
