### ISSUE TITLE
essentials methods ???

### ISSUE THREAD

**Issue by atheleron** [alecgorge/jsonapi#395]
Im trying to call essentials plugin method that are from <a href="http://mcjsonapi.com/apidocs/">api docs</a>
like <b>essentials.users.seen</b> in php api but it seems that method doesn't exist ??

I just want to get information when last time user was seen in game to my website

im using JSONAPI-5.6.0-mc1.7.9-R0.2-SNAPSHOT.jar

**Comment by JayeGame** [comment]
J'ai le même problème :(
