### ISSUE TITLE
Error JsonAPI + No count member online in my website

### ISSUE THREAD

**Issue by white35** [alecgorge/jsonapi#412]
Hello,
I'm french and I don't have a good English xD
In my "console" i can see this:
"29.10 15:30:59 [Server] INFO [API Call] 62.210.45.226: method=players.online.names?args=[]
29.10 15:30:59 [Server] INFO [API Call] 62.210.45.226: method=players.online.limit?args=[]
29.10 15:30:59 [Server] WARN at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
29.10 15:30:59 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:489)
29.10 15:30:59 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:583)
29.10 15:30:59 [Server] WARN at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283)
29.10 15:30:59 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:635)
29.10 15:30:59 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
29.10 15:30:59 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftFuture.run(CraftFuture.java:89)
29.10 15:30:59 [Server] WARN at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
29.10 15:30:59 [Server] WARN at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
29.10 15:30:59 [Server] WARN at java.lang.Class.getDeclaredField(Class.java:1948)
29.10 15:30:59 [Server] WARN java.lang.NoSuchFieldException: length
29.10 15:30:58 [Server] INFO [API Call] 62.210.45.226: method=players.online.count?args=[]
29.10 15:30:39 [Server] INFO [API Call] 62.210.45.226: method=players.online.names?args=[]
29.10 15:30:39 [Server] INFO [API Call] 62.210.45.226: method=players.online.limit?args=[]
29.10 15:30:39 [Server] WARN at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
29.10 15:30:39 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:489)
29.10 15:30:39 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:583)
29.10 15:30:39 [Server] WARN at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283)
29.10 15:30:39 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:635)
29.10 15:30:39 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
29.10 15:30:39 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftFuture.run(CraftFuture.java:89)
29.10 15:30:39 [Server] WARN at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
29.10 15:30:39 [Server] WARN at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
29.10 15:30:39 [Server] WARN at java.lang.Class.getDeclaredField(Class.java:1948)
29.10 15:30:38 [Server] WARN java.lang.NoSuchFieldException: length
29.10 15:30:37 [Server] INFO [Membre][]juju03: ok
29.10 15:30:36 [Server] INFO [API Call] 62.210.45.226: method=players.online.count?args=[]
29.10 15:30:33 [Server] INFO [API Call] 62.210.45.226: method=players.online.names?args=[]
29.10 15:30:33 [Server] INFO [API Call] 62.210.45.226: method=players.online.limit?args=[]
29.10 15:30:33 [Server] WARN at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
29.10 15:30:33 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:489)
29.10 15:30:33 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:583)
29.10 15:30:33 [Server] WARN at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283)
29.10 15:30:33 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:635)
29.10 15:30:33 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
29.10 15:30:33 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftFuture.run(CraftFuture.java:89)
29.10 15:30:33 [Server] WARN at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
29.10 15:30:33 [Server] WARN at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
29.10 15:30:33 [Server] WARN at java.lang.Class.getDeclaredField(Class.java:1948)
29.10 15:30:33 [Server] WARN java.lang.NoSuchFieldException: length
29.10 15:30:33 [Server] INFO [API Call] 62.210.45.226: method=players.online.count?args=[]"

In my website (http://block-fight.fr), the rewards sytem works for votes , auto shop also works but I do not see the number of people connected. 
All my ports are open, I use SamantCMS, version git-Spigot-1519 (MC: 1.7.9) (Implementing API version 1.7.9-R0.3-SNAPSHOT) and JSONAPI-5.6.0-mc1.7.9-R0.2-SNAPSHOT.jar

Bests Regards, thenks to help me. Damien/white35/shokomium

**Comment by alecgorge** [comment]
This should be fixed in the latest builds: 

New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.
