### ISSUE TITLE
Latest messages / formatted messages return messages from cancelled chat events

### ISSUE THREAD

**Issue by OffLuffy** [alecgorge/jsonapi#416]
I'm not entirely sure if this is intended, but it's not entirely useful, as far as I can tell. I'm using JSONAPI v5.6.0 and when calling the server.chat.latest or server.formatted_chat.latest, it also includes messages that were sent in cancelled chat events. At least this is what I've presumed by what is happening.

I've written a chat box that simply streams chat to a certain web page and there are some messages that show up there that I don't want. There are 2 specific events in particular I've noticed this with: when a user talks in a WorldGuard region where sending chat is disabled, and when using the admin chat feature in mcMMO (with admin chat locked on and typing normally, not when using the /a command followed by a message), presumably functions the same with party chat and any other cancelled chat events.

I would suggest it ignore cancelled events or add an 'isCancelled' boolean object to the data arrays to at least provide a way to filter out those cancelled messages.

**Comment by alecgorge** [comment]
I added isCancelled in the latest builds:

New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.
