### ISSUE TITLE
Players Log out

### ISSUE THREAD

**Issue by TheKillHDmc** [alecgorge/jsonapi#420]
Hello,

Sorry for my English, I speak French.

Sometimes, my players log out for no reason ( 3/4 of my players ) 

Logs : http://pastebin.com/Kw99Aq2Q

**Comment by lifehome** [comment]
Next time, cover up the IP addresses first.

**Comment by TheKillHDmc** [comment]
f*ck :x

**Comment by alecgorge** [comment]
Try the latest build:

New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.

**Comment by TheKillHDmc** [comment]
Ok thanks ill try
