### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by Freymuth** [alecgorge/jsonapi#423]
Hi,

when release you a new build on Jenkins? The last one is from december ...

Greetings

**Comment by electronicboy** [comment]
#418 
Already a ticket open regarding 1.8...

**Comment by lifehome** [comment]
#418

**Comment by lifehome** [comment]
Duplicate #418

**Comment by alecgorge** [comment]
New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.
