### ISSUE TITLE
xss vulnerability

### ISSUE THREAD

**Issue by Talaren** [alecgorge/jsonapi#433]
after install the jsonapi the security scanner gives a high risk warning out.

example on console
```javascript
curl "http://server:25565/foo.bar?test=<SCRIPT>alert('cross_scripting_successful')</SCRIPT>"
```
Answer from server
```javascript
/foo.bar?test=<SCRIPT>alert('cross_scripting_successful')</SCRIPT> wasn't found. This is a Minecraft server. HTTP on this port by JSONAPI. JSONAPI by Alec Gorge.
```

this can use for cross site scripting.
please do not send back the input from the url
http://en.wikipedia.org/wiki/Cross-site_scripting

Output from Scanner:

Web Server Generic Cross-Site Scripting Vulnerability [ Web Servers ] Risk: Medium

Port: 25565
The remote web server seems to be vulnerable to the Cross Site Scripting vulnerability (XSS). The vulnerability is caused
by the result returned to the user when a non-existing file is requested (e.g. the result contains the JavaScript provided
in the request).
The vulnerability would allow an attacker to make the server present the user with the attacker s JavaScript/HTML code.
Since the content is presented by the server, the user will give it the trust
level of the server (for example, the trust level of banks, shopping centers, etc. would usually be high).

Multiple Cross Site Scripting and SQL Injection vulnerabilities in XRMS [ Web application abuses ] Risk: High

Port: 25565
Summary:
XRMS is a web-based application for managing business entities such as
employees, customers, contacts, activities.
The application is vulnerable to simple Cross Site Scripting, which can
be used for several isues.
Solution:
Upgrade to the latest version of this software

**Comment by alecgorge** [comment]
This is not an XSS vulnerability.

1. The query string is not printed out exactly as was input. It is encoded to prevent XSS so it will never be executed:
```
/foo.bar?test=%3CSCRIPT%3Ealert(%27cross_scripting_successful%27)%3C/SCRIPT%3E wasn't found. This is a Minecraft server. HTTP on this port by JSONAPI. JSONAPI by Alec Gorge.
```
2. The output is of type text/plain, so it wouldn't be executed anyway even if it wasn't encoded.
3. There is no SQL Injection vulnerability. There isn't SQL in this project at all!

Printing out the whole URL may not be the best idea but it definitely isn't vulnerable to XSS.
