### ISSUE TITLE
JSONAPI jar file renamed .restricted when starting server

### ISSUE THREAD

**Issue by Capri205** [alecgorge/jsonapi#461]
Hi. I am working on installation of the JSONAPI plugin for a spigot 1.8.8 server and when I restart the server it renames the plugin to JSONAPI.jar.restricted for some reason and doesn't load it. There's nothing at all in the server log to indicate why. I'm not sure if it's a spigot thing or problem with the jar file I downloaded. If I rename the jar file back to just .jar and issue a /reload command from the console, the server will load the plugin and I can issue some test curl commands just fine, however, reloading introduces problems for other plugins so that's not the correct way. Any idea why spigot renames this jar file at startup?

Again, apologies if this is more a spigot issue and not appropriate for this forum.

Cheers.

**Comment by electronicboy** [comment]
Speak to your hosting provider, this is a function inside the hosting panel McMyAdmin and potentially others.

**Comment by Capri205** [comment]
You are correct. The McMyAdmin console identifies this plugin as a hazard or a banned plugin and it will not activate it. Thank you very much for the prompt reply.
