### ISSUE TITLE
Adding an API method

### ISSUE THREAD

**Issue by blackphreak** [alecgorge/jsonapi#462]
Plugin(Methods.java): http://pastebin.com/pHPmANke
Plugin(Plugins.java): http://pastebin.com/LUfDsujg

when I tested on my server, I got this: http://pastebin.com/Nu9Cfesa

can someone help me pls..?
(I'm just a newbie)

my server is now using "spigot 1.8.5" and "JSONAPI 5.6.0 - for 1.8"

**Comment by alecgorge** [comment]
did you make sure jsonapi is listed as a dependency of your plugin so that it is loaded first

**Comment by blackphreak** [comment]
I found that where the error come from.
becuz of my plugin.yml, I put a "s" at the argument: depend, so that it cant load as dependency.
(sorry for my bad English -w-)
btw, thx for your help. :)
