### ISSUE TITLE
1 year after, any release ?

### ISSUE THREAD

**Issue by JohOply** [alecgorge/jsonapi#467]
Hi guys

I want to know if a release is schedule in the next weeks ? Even if JSONAPI works, there is a lots of imperfections and errors in logs.

Thanks in advance for any answers, and above all thanks for this plugin.

**Comment by krisdb2009** [comment]
Author probably abandoned it. Check out this fork,  https://github.com/d03n3rfr1tz3/Bukkit.JSONAPI

**Comment by JohOply** [comment]
I don't understand how dev can abandon JSONAPI without warned anybody, it's a pity :(

Thank you for the link, i will try it ! Do you use it?

**Comment by krisdb2009** [comment]
I use it yes.
