### ISSUE TITLE
Error during compilation - missing dependencies

### ISSUE THREAD

**Issue by cyberbobjr** [alecgorge/jsonapi#481]
Hi everybody, 
i've cloned the repo and i'm trying to compile the source, but i have many errors of missing dependencies :
M2_REPO/com/comphenix/executors/BukkitExecutors/1.0.0/BukkitExecutors-1.0.0.jar
M2_REPO/com/comphenix/protocol/ProtocolLib/3.6.3-SNAPSHOT/ProtocolLib-3.6.3-SNAPSHOT.jar
M2_REPO/com/google/code/gson/gson/2.3/gson-2.3.jar
M2_REPO/net/ess3/Essentials/2.13.1/Essentials-2.13.1.jar
M2_REPO/net/milkbowl/vault/Vault/1.4.1/Vault-1.4.1.jar
M2_REPO/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar

I'm a beginner in java dev, does this lib must be present for building the JSON-API.JAR ?
if true, where can i get these lib ?

Thanks for your help
Best regards
cab

**Comment by Acrodeminecraft** [comment]
UP

**Comment by alecgorge** [comment]
Compiling is done via a maven project and if you are using an IDE such as eclipse you will need to install their maven integration plugin so that it can download the dependencies properly
