### ISSUE TITLE
Error with lastest Spigot 1.10 Build

### ISSUE THREAD

**Issue by dadee971** [alecgorge/jsonapi#489]
Hi,

There are errors on server starts with lastest Spigot 1.10 build.

- JSONAPI: [Server thread/INFO]: [JSONAPI] Enabling JSONAPI v5.7.0
- SPIGOT:  CraftBukkit version git-Spigot-e50d38c-02f4218 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT) You are running the latest version

**Error log:**

http://pastebin.com/jstatrrA

**Comment by alecgorge** [comment]
Please try a new build from here: https://ci.alecgorge.com/job/JSONAPI/lastSuccessfulBuild/artifact/builds/Spigot-all/
