### ISSUE TITLE
Builds and docs

### ISSUE THREAD

**Issue by moose51789** [alecgorge/jsonapi#497]
So it seems this has been completely abandoned by the dev but i see hes merged a few pull requests.  Is this build anywhere to download?  Same with docs, be nice to be able to still see them somewhere considering he took the domain offline.

**Comment by dartasen** [comment]
I'm so kind : http://www.mediafire.com/file/8n2xmlgmpa0b4hv/JSONAPI-1.11.2.jar 🥇

**Comment by moose51789** [comment]
You are awesome.  I tried to build from the sourcebut maven was complaining about something and i didn't have much time to investigate

**Comment by alecgorge** [comment]
@moose51789 builds can always be downloaded at https://ci.alecgorge.com/job/JSONAPI/lastSuccessfulBuild/

**Comment by alecgorge** [comment]
@moose51789 sorry about the domain being down. I had moved servers a while back and forgot to update the DNS records. mcjsonapi.com should work again soon
